version: '3.1'

services:
  website:
    image: nicocourts/website:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/nicocourts.com/fullchain.pem:/etc/letsencrypt/live/nicocourts.com/fullchain.pem
      - /etc/letsencrypt/live/nicocourts.com/privkey.pem:/etc/letsencrypt/live/nicocourts.com/privkey.pem
      - /docker-volumes/etc/letsencrypt/live/4n1.co/fullchain.pem:/etc/letsencrypt/live/4n1.co/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/4n1.co/privkey.pem:/etc/letsencrypt/live/4n1.co/privkey.pem
      - /etc/letsencrypt/live/api.nicocourts.com/fullchain.pem:/etc/letsencrypt/live/api.nicocourts.com/fullchain.pem
      - /etc/letsencrypt/live/api.nicocourts.com/privkey.pem:/etc/letsencrypt/live/api.nicocourts.com/privkey.pem
      - /home/omfg_lag/img:/usr/share/nginx/html/img
      - /home/omfg_lag/.well-known/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge
  
  
  api:
    image: nicocourts/server:latest
    volumes:
      - /home/omfg_lag/pki/public.pem:/etc/pki/public.pem
      - /home/omfg_lag/img:/etc/img
      - /home/omfg_lag/.well-known/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge

  mongodb:
    image: mongo:latest
    volumes:
      - /home/omfg_lag/db:/data/db
